modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="crafty_additions"
version="1.0.0"
displayName="Crafty Additions"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Diego Kaujon, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.crafty_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



